import type { MetadataRoute } from 'next';

export default function manifest(): MetadataRoute.Manifest {
  return {
    name:             'Hassan – Frontend Developer Portfolio',
    short_name:       'Portfolio',
    description:      'Passionate Frontend Developer specializing in React, Next.js, and modern web technologies.',
    start_url:        '/',
    scope:            '/',
    display:          'standalone',
    orientation:      'portrait',
    background_color: '#09090b',
    theme_color:      '#9333ea',
    categories:       ['portfolio', 'developer'],
    lang:             'en',
    icons: [
      {
        // SVG fallback for browsers that support it
        src:     '/icon.svg',
        sizes:   'any',
        type:    'image/svg+xml',
        purpose: 'any',
      },
      {
        // Generated by app/apple-icon.tsx → served at /apple-icon
        src:     '/apple-icon',
        sizes:   '180x180',
        type:    'image/png',
        purpose: 'any',
      },
      {
        // Generated by app/icon.tsx → served at /icon
        src:     '/icon',
        sizes:   '512x512',
        type:    'image/png',
        purpose: 'maskable',
      },
    ],
  };
}
